# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f02440bddb2b41649b4ebafd81ce264bd0911763d60d63a6bfb4c92c92bbaaf14b36c3e85df4934dcc0d60e49bc4ad16b271625b30c949d6fbaec555b66f057

test:
  secret_key_base: 4f00c27a3b4bc9d4023bcaa937d739421fc2e2bf18af0131828c6917b2afa90962c536f399ce25d1c762c5057f2fbdd660bf934eeb27c0916f8311a8ce855739

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
